name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: makeBuild
      working-directory: .
      run: mkdir build
    - name: CMake generation
      working-directory: .
      run: cd build && cmake ..
    - name: Compilation
      working-directory: .
      run: cd lib && ls && cd .. && cd build && make
    - name: runTests
      working-directory: .
      run: |
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          cd build && ctest -V

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install CMake
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' || exit 1
    - name: CMake Generation
      run: cmake -S . -B build -G "Visual Studio 17 2022"
    - name: Build Solution
      run: |
        msbuild MinesweeperVS/MinesweeperVS.sln /p:Configuration=Release /p:Platform=x64
    - name: Run Tests
      run: |
        cd MinesweeperVS\x64\Release
        .\MinesweeperVS-tests.exe
